/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Chamath
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Home
     */
    Connection con=ConnectionManager.getConnection();
    ResultSet rs=null;
    PreparedStatement pst=null;
    public Login() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        topLogo = new javax.swing.JLabel();
        welcomeText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        forgotText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(540, 240, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/arrow.png"))); // NOI18N
        jButton1.setToolTipText("Back");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 330, 60, -1));

        topLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/top.png"))); // NOI18N
        jPanel2.add(topLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 80));

        welcomeText.setFont(new java.awt.Font("Corbel Light", 0, 24)); // NOI18N
        welcomeText.setText("Welcome Back");
        jPanel2.add(welcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Sign in to Continue");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        logBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/signBtn.png"))); // NOI18N
        logBtn.setBorder(null);
        logBtn.setBorderPainted(false);
        logBtn.setContentAreaFilled(false);
        logBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logBtn.setFocusPainted(false);
        logBtn.setIconTextGap(0);
        logBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtnActionPerformed(evt);
            }
        });
        jPanel2.add(logBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 180, 70));

        jLabel5.setText("User Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        userName.setForeground(new java.awt.Color(102, 102, 102));
        userName.setBorder(null);
        userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameKeyPressed(evt);
            }
        });
        jPanel2.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 350, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 350, 10));

        jLabel6.setText("Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        pass.setToolTipText("");
        pass.setBorder(null);
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 350, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 350, 10));

        forgotText.setForeground(new java.awt.Color(0, 102, 204));
        forgotText.setText("Forgot Password?");
        forgotText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotTextMouseClicked(evt);
            }
        });
        jPanel2.add(forgotText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean isUser(){
        try{
            con=ConnectionManager.getConnection();
            String std="Select * from student where userName=? and password=? or email=? and password=?";
            pst=con.prepareStatement(std);
            pst.setString(1,userName.getText());
            pst.setString(3,userName.getText());
            pst.setString(2,new String(pass.getPassword()));
            pst.setString(4,new String(pass.getPassword()));
            //int rst=pst.executeUpdate();
            rs=pst.executeQuery();
            if(rs.next()){
                return true;
            }
        }
        catch(Exception ex){
            System.out.println(ex);
        }
        finally{
            try {
                rs.close();
                pst.close();
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return false;
    }
    private boolean isAdmin(){
        try{
            con=ConnectionManager.getConnection();
            String adm="Select * from admin where aid=? and password=?";
            pst=con.prepareStatement(adm);
            pst.setString(1,userName.getText());
            pst.setString(2,new String(pass.getPassword()));
            //int rst=pst.executeUpdate();
            rs=pst.executeQuery();
            if(rs.next()){
                return true;
            }
        }
        catch(Exception ex){
            System.out.println(ex);
        }
        finally{
            try {
                rs.close();
                pst.close();
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return false;
    }
    private void logBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtnActionPerformed
        if(isUser()){
            new User(userName.getText()).setVisible(true);
            this.setVisible(false);
        }
        else if(isAdmin()){
            new Master().setVisible(true);
            Master.welcome.setText(userName.getText());
            this.setVisible(false);
        }
        else{
                JOptionPane.showMessageDialog(this,"Wrong Password or Username");
        }
    }//GEN-LAST:event_logBtnActionPerformed

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
        logBtn.doClick();
        userName.setText("");
        pass.setText("");
        }
    }//GEN-LAST:event_passKeyPressed

    private void userNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameKeyPressed
        if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
        logBtn.doClick();
        userName.setText("");
        pass.setText("");
        }
    }//GEN-LAST:event_userNameKeyPressed

    private void forgotTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotTextMouseClicked
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_forgotTextMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            pass.setEchoChar((char)0);
        }
        else{
            pass.setEchoChar('\u25CF');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                   if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forgotText;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logBtn;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel topLogo;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
