/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;



import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Chamath
 */
public class Register extends javax.swing.JFrame {
Connection con=ConnectionManager.getConnection();
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form Register
     */

    public Register() {
        initComponents();
        addComboItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        fName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        course = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        telNo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        subBtn = new javax.swing.JButton();
        welcomeText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        topLogo = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        date = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(700, 800));
        setPreferredSize(new java.awt.Dimension(700, 830));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("First Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 260, -1));

        lName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lName.setForeground(new java.awt.Color(102, 102, 102));
        lName.setText("Enter Last Name");
        lName.setBorder(null);
        lName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lNameFocusGained(evt);
            }
        });
        jPanel2.add(lName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 610, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Date of Brith");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 340, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 610, 10));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 610, 10));

        fName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fName.setForeground(new java.awt.Color(102, 102, 102));
        fName.setText("Enter First Name");
        fName.setBorder(null);
        fName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fNameFocusGained(evt);
            }
        });
        jPanel2.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 610, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Last Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 320, -1));

        year.setEditable(true);
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year" }));
        year.setBorder(null);
        year.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        year.setFocusable(false);
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        jPanel2.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 130, 30));

        course.setEditable(true);
        course.setBorder(null);
        course.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        course.setFocusable(false);
        jPanel2.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 610, 40));

        month.setEditable(true);
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month" }));
        month.setBorder(null);
        month.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        month.setFocusable(false);
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        jPanel2.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("E-mail");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 290, -1));

        mail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mail.setForeground(new java.awt.Color(102, 102, 102));
        mail.setText("Enter E-mail");
        mail.setBorder(null);
        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFocusGained(evt);
            }
        });
        jPanel2.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 610, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 610, 10));

        jLabel9.setText("Telephone Number");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 370, -1));

        telNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        telNo.setForeground(new java.awt.Color(102, 102, 102));
        telNo.setText("Enter your Phone Number");
        telNo.setBorder(null);
        telNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telNoFocusGained(evt);
            }
        });
        jPanel2.add(telNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 610, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 610, 10));

        subBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/sbmtBtn.png"))); // NOI18N
        subBtn.setBorderPainted(false);
        subBtn.setContentAreaFilled(false);
        subBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                subBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                subBtnMouseReleased(evt);
            }
        });
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });
        jPanel2.add(subBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 710, 180, 60));

        welcomeText.setFont(new java.awt.Font("Corbel Light", 0, 24)); // NOI18N
        welcomeText.setText("Hello, Let's Get Started");
        jPanel2.add(welcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Fill in the Details to Continue");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        topLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/top.png"))); // NOI18N
        jPanel2.add(topLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 80));

        nic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nic.setForeground(new java.awt.Color(102, 102, 102));
        nic.setBorder(null);
        nic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nicFocusGained(evt);
            }
        });
        jPanel2.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 610, 30));

        jLabel10.setText("National Identity Card Number");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 380, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 610, 10));

        date.setEditable(true);
        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date" }));
        date.setBorder(null);
        date.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        date.setFocusable(false);
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 130, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Course");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 340, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void addComboItems(){
        //String[] sub={"Software Engineering","Computer Engineering","Computer Science"};
        for(int i=1990;i<=2020;i++){
            year.addItem(String.valueOf(i));
        }
        for(int i=1;i<=12;i++){
            month.addItem(String.valueOf(i));
        }
        for(int i=1;i<=31;i++){
            date.addItem(String.valueOf(i));
        }
    try{
        pst=con.prepareStatement("select * from course");
        rs=pst.executeQuery();
        while(rs.next()){
            course.addItem(rs.getString(2));
    }
    } catch (Exception ex) {
        System.out.println(ex);
    }
    finally{
        try{
        rs.close();
        pst.close();
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }
        //DefaultComboBoxModel dm=new DefaultComboBoxModel(sub);
        //crsCombo.setModel(dm);
    }
    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        if(validateFeild()){
            String dob=(String) year.getSelectedItem()+"-"+month.getSelectedItem()+"-"+date.getSelectedItem();
            new ConnectionManager().insertRegister(fName.getText(), lName.getText(),nic.getText(), dob, mail.getText(),course.getSelectedItem().toString(),telNo.getText());
            JOptionPane.showMessageDialog(this,"Registered Successfully, We sent you an Email Please check your Inbox");
            Mail email=new Mail(mail.getText(),"CNC INSTITUTE","You have been registered to the CNC Institute, We will send you an email as soon as the enrollment is done.");
            email.doTest();
            this.dispose();
        }
    }//GEN-LAST:event_subBtnActionPerformed

    private void subBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subBtnMouseReleased
        ImageIcon II=new ImageIcon(getClass().getResource("/StudentManagement/sbmtBtnHover.png"));
        subBtn.setIcon(II);
    }//GEN-LAST:event_subBtnMouseReleased

    private void subBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subBtnMousePressed
        ImageIcon II=new ImageIcon(getClass().getResource("/StudentManagement/sbmtBtnPressed.png"));
        subBtn.setIcon(II);
    }//GEN-LAST:event_subBtnMousePressed

    private void subBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subBtnMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/StudentManagement/sbmtBtn.png"));
        subBtn.setIcon(II);
    }//GEN-LAST:event_subBtnMouseExited

    private void subBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subBtnMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/StudentManagement/sbmtBtnHover.png"));
        subBtn.setIcon(II);
    }//GEN-LAST:event_subBtnMouseEntered

    private void telNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telNoFocusGained
        telNo.setText("");
    }//GEN-LAST:event_telNoFocusGained

    private void mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusGained
        mail.setText("");
    }//GEN-LAST:event_mailFocusGained

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        month.removeItemAt(0);
    }//GEN-LAST:event_monthActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        year.removeItemAt(0);
    }//GEN-LAST:event_yearActionPerformed

    private void fNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNameFocusGained
        fName.setText("");
    }//GEN-LAST:event_fNameFocusGained

    private void lNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lNameFocusGained
        lName.setText("");
    }//GEN-LAST:event_lNameFocusGained

    private void nicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nicFocusGained

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed
    
    public static boolean isNumeric(final String str) {

        // null or empty
        if (str == null || str.length() == 0) {
            return false;
        }

        for (char c : str.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }

        return true;

    }
    private boolean validateFeild(){
        String dt=(String) date.getSelectedItem();
        String mn=(String) month.getSelectedItem();
        String yr=(String) year.getSelectedItem();
           if(isNumeric(dt)==false||isNumeric(mn)==false||isNumeric(yr)==false){
               JOptionPane.showMessageDialog(this,"Please Select your Date of Birth");
               return false;
           }
           else if(fName.getText().isEmpty()||lName.getText().isEmpty()||mail.getText().isEmpty()||telNo.getText().isEmpty()){
               JOptionPane.showMessageDialog(this,"Please Fill in the required Fields");
               return false;
           }
           else if(new ConnectionManager().validateMail(mail.getText())==false){
               JOptionPane.showMessageDialog(this,"Please Enter a Valid Email");
               return false;
           }
    return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> course;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JTextField fName;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField lName;
    private javax.swing.JTextField mail;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField nic;
    private javax.swing.JButton subBtn;
    private javax.swing.JTextField telNo;
    private javax.swing.JLabel topLogo;
    private javax.swing.JLabel welcomeText;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
